name: 'Backport Action'
description: 'Backport commits from a merged Pull Request to another branch with a label'
branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{github.token}}
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
